import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import LoginForm from "../src/Login/LoginForm";
import Profile from "../src/Login/Profile";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { loginDone } = useSelector((state) => state.user);
  const [todos, setTodos] = useState([]);

  useEffect(() => {
    const fetchTodos = async () => {
      const res = await fetch("https://jsonplaceholder.typicode.com/todos");
      const data = await res.json();
      setTodos(data);
    };
    fetchTodos();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>키메라 next.js 공부하기!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <>{loginDone ? <Profile /> : <LoginForm />}</>
        </div>
        <div className={styles.grid}>
          {todos.length === 0 ? (
            <div>Loading...</div>
          ) : (
            todos.map((todo) => (
              <div key={todo.id}>
                <p>
                  {todo.id} : {todo.title}
                </p>
              </div>
            ))
          )}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{"공대키메라"}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
